version: "3.8" # 설치된 docker 버전에 따라 다릅니다!

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - /usr/local/var/mongodb:/data/db
    restart: "unless-stopped" 
  proxy:
    image: nginx:latest   # 최신 버전의 Nginx 사용
    container_name: proxy # container 이름은 proxy
    ports: 
      - "1004:1004"
      - "2004:2004"           # 80번 포트를 host와 container 맵핑
    volumes:
      - ./proxy/cert.crt:/etc/nginx/cert.crt
      - ./proxy/private.key:/etc/nginx/private.key
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf # nginx 설정 파일 volume 맵핑
    restart: "unless-stopped" # 내부에서 에러로 인해 container가 죽을 경우 restart
  express:
    build:
      context: ./server  # 빌드할 Dockerfile이 위치한 경로
    container_name: express
    # expose: 
    #   - "3000"           # 다른 컨테이너에게 3000번 포트 open
    volumes:
      - ./server:/server # host <-> container의 source 디렉토리를 공유
      - /server/node_modules # !!!!!!!! Dockerfile 설명에서 다시 설명합니다.
    restart: "unless-stopped"
